Backend profess&cities
MSU-Python-Lab/FinalProject pull request #8
Opened 2022-06-13 11:38 UTC by BarBoley

Created methods for Professions and Cities

2022-06-13 12:23 UTC, Hrustyaschiy requested changes

2022-06-13 12:23 UTC, Hrustyaschiy commented on iconic/UserProfile/urls.py
> +         name='cities'),
Delete "name" arguments

2022-06-13 12:23 UTC, Hrustyaschiy commented on iconic/UserProfile/views.py
> +        return Response(serializer.data)
All methods that process requests have arguments (self, request), also two methods that process the same request (GET) cant be in one class

2022-06-13 12:23 UTC, Hrustyaschiy commented on iconic/UserProfile/views.py
> +        return Response(serializer.data)
All methods that process requests have arguments (self, request), also two methods that process the same request (GET) cant be in one class

2022-06-13 13:02 UTC, Hrustyaschiy requested changes
Also i want that request returns IDs of entries

2022-06-13 13:02 UTC, Hrustyaschiy commented on iconic/UserProfile/serializers.py
> +    class Meta:
Names of fields in serializers should be same as names of fields inj models

2022-06-13 13:02 UTC, Hrustyaschiy commented on iconic/UserProfile/views.py
> +        return Response(serializer.data)
You forgot "request" argument

2022-06-13 13:02 UTC, Hrustyaschiy commented on iconic/UserProfile/views.py
> +        return Response(serializer.data)
You forgot "request" argument

2022-06-13 13:02 UTC, Hrustyaschiy commented on iconic/UserProfile/views.py
> +        return Response(serializer.data)
You cant use data.id, use data['id'] istead of it

2022-06-13 13:02 UTC, Hrustyaschiy commented on iconic/UserProfile/views.py
> +            return Response(serializer.errors)
You cant use data.id, use data['id'] istead of it

2022-06-13 13:02 UTC, Hrustyaschiy commented on iconic/UserProfile/views.py
> +        if serializer.is_valid():
You cant use data.id, use data['id'] istead of it

2022-06-13 13:02 UTC, Hrustyaschiy commented on iconic/UserProfile/views.py
> +
You cant use data.id, use data['id'] istead of it

2022-06-13 13:02 UTC, Hrustyaschiy commented on iconic/UserProfile/views.py
> +
You cant use data.id, use data['id'] istead of it

2022-06-13 13:02 UTC, Hrustyaschiy commented on iconic/UserProfile/views.py
> +            return Response(serializer.data)
You cant use data.id, use data['id'] istead of it

2022-06-13 13:02 UTC, Hrustyaschiy commented on iconic/UserProfile/views.py
> +            return Response(serializer.data)
You cant use data.id, use data['id'] istead of it

2022-06-13 13:02 UTC, Hrustyaschiy commented on iconic/UserProfile/views.py
> +
You cant use data.id, use data['id'] istead of it

2022-06-13 15:38 UTC, Hrustyaschiy requested changes

2022-06-13 15:38 UTC, Hrustyaschiy commented on iconic/UserProfile/urls.py
> +    path('cities/edit', views.CitiesEdit.as_view()),
add a slash at the end of edit in both paths

2022-06-13 15:38 UTC, Hrustyaschiy commented on iconic/UserProfile/views.py
> +    def get(self, request):
Want comments

2022-06-13 15:38 UTC, Hrustyaschiy commented on iconic/UserProfile/serializers.py
> +    class Meta:
Want comments

2022-06-13 15:38 UTC, Hrustyaschiy commented on iconic/UserProfile/views.py
> +    def get(self, request):
Comments

2022-06-13 15:38 UTC, Hrustyaschiy commented on iconic/UserProfile/views.py
> +    def get(self, request):
Comments

2022-06-13 15:55 UTC, Hrustyaschiy approved these changes

2022-06-13 16:42 UTC, Hordd-Scratch commented on iconic/UserProfile/views.py
> +        return Response(serializer.data)
I want the status of the response. Look at the code from the updated dev as an example

2022-06-13 16:42 UTC, Hordd-Scratch commented on iconic/UserProfile/views.py
> +            return Response(serializer.errors)
I want the status of the response.

2022-06-13 16:42 UTC, Hordd-Scratch commented on iconic/UserProfile/views.py
> +            return Response(serializer.errors)
I want the status of the response.

2022-06-13 16:42 UTC, Hordd-Scratch commented on iconic/UserProfile/views.py
> +        return Response()
I want the status of the response.

2022-06-13 16:42 UTC, Hordd-Scratch commented on iconic/UserProfile/views.py
> +        return Response(serializer.data)
I want the status of the response.

2022-06-13 16:42 UTC, Hordd-Scratch commented on iconic/UserProfile/views.py
> +        return Response(serializer.data)
I want the status of the response.

2022-06-13 16:42 UTC, Hordd-Scratch commented on iconic/UserProfile/views.py
> +            return Response(serializer.data)
I want the status of the response.

2022-06-13 16:43 UTC, Hordd-Scratch commented on iconic/UserProfile/views.py
> +            return Response(serializer.errors)
I want the status of the response.

2022-06-13 16:43 UTC, Hordd-Scratch commented on iconic/UserProfile/views.py
> +            return Response(serializer.errors)
I want the status of the response.

2022-06-13 16:43 UTC, Hordd-Scratch commented on iconic/UserProfile/views.py
> +        return Response()
I want the status of the response.

2022-06-13 16:43 UTC, Hordd-Scratch commented on iconic/UserProfile/views.py
> +        return Response(serializer.data)
I want the status of the response.

2022-06-13 17:07 UTC, Hordd-Scratch approved these changes

2022-06-14 04:24 UTC, Hrustyaschiy approved these changes

2022-06-14 04:44 UTC, merged